services:

  drives:

    container_name: drives

    image: drives:0.0.1-SNAPSHOT
    pull_policy: if_not_present

    volumes:
      - ./data:/root/data

    restart: always

    networks:
      - traefik

    env_file: "docker-drives-env.txt"

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.drives.rule=Host(`drives.schrell.de`)"
      - "traefik.http.routers.drives.entrypoints=websecure"
      - "traefik.http.routers.drives.tls.certresolver=myresolver"
      - "traefik.http.routers.drives.service=drives-service"
      - "traefik.http.services.drives-service.loadbalancer.server.port=8080"
      - "traefik.http.routers.drives.middlewares=drives-fwd@file"
      - "autoheal=false"

networks:
  traefik:
    external: true