spring:
  sql:
    init:
      mode: always
  application:
    name: Fahrten
  datasource:
    url: jdbc:h2:file:~/data/drives
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    show-sql: true
  web:
    resources:
      static-locations: classpath:/public/browser
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "718036740225-nccd9egms4lp44bdqpt0dh37g8gd3385.apps.googleusercontent.com"
            client-secret: "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"
logging:
  level:
    org:
      springframework:
        security: TRACE

server:
  tomcat:
    remoteip:
      remote-ip-header: X-Forwarded-For
      protocol-header: X-Forwarded-Proto