spring:
  sql:
    init:
      mode: always
  application:
    name: Fahrten
  datasource:
    url: jdbc:h2:file:${DRIVES_DATABASE_PATH:~/data/drives}
    driverClassName: org.h2.Driver
    username: ${DRIVES_DATABASE_USERNAME:sa}
    password: ${DRIVES_DATABASE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  web:
    resources:
      static-locations: classpath:/public/browser